[package]
name = "ju-rust-wasm"
version = "0.1.0"
authors = ["Juching"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]  # cdylib 编译目标

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.63"  # WebAssembly 辅助工具

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.6", optional = true }  # 错误输出辅助工具

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
wee_alloc = { version = "0.4.5", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.13"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"

[dependencies.web-sys]  # Web 接口定义
version = "0.3"
features = [
  "console",
]
